THANK_STIKERS = ["CAACAgUAAxkBAAEDVS9hmmQwaqz1LSAOLm05l0Nj-DTs3QACUgAD3HgMCAUPio2qQp6ZIgQ",
                     "CAACAgIAAxkBAAEDVTFhmmRQZAzPCHyHt3FgzJm1v0j0EQACWwADRA3PF2b6FTNrHmEEIgQ",
                     "CAACAgIAAxkBAAEDVTNhmmUUpP2Rgm6WQoGWVNYMy2P3tgACBAADTLa2ENAxQE5uzpXkIgQ",
                     "CAACAgIAAxkBAAEDVTVhmmUp8Ch2O9S3RB8sePpfK7RSHwACXToAAuCjggdWcwXYdRVtnyIE",
                     "CAACAgIAAxkBAAEDVTdhmmVURjhCB3pABqWKIJpBjZxAXQACEAwAAhU1sUjU_2ZvX6VsNSIE",
                     "CAACAgIAAxkBAAEDVTlhmmXBNYnP7YOqWMCI1jFNpTCDUAACPAEAAqMpBQgwhZuIXj623iIE",
                     "CAACAgIAAxkBAAEDVTthmmYDxpVPnt4KU3N3m7UpXSlWuwACFwEAAjVTLj-mhPstuPmmMCIE",
                     "CAACAgIAAxkBAAEDVT1hmmattcgJr-drNsIWvARm_ocDNwACgAwAAhPOSUi9DGQBhp6OciIE",
                     "CAACAgIAAxkBAAEDVUFhmmdQ0A5JjUXjVuP5g2rem1eL5AACaC8AAuCjggepxr_S3AP41CIE",
                     "CAACAgIAAxkBAAEDVUNhmmdd1awVcAPTerLP4PR2TxMDGQACZRoAAuCjggdQ1otg-UaIlyIE",
                     "CAACAgIAAxkBAAEDVUVhmmdxTa3LwygTlXIeO5EiQf8ZrgACchIAAkblqUjyTBtFPtcDUSIE",
                     "CAACAgQAAxkBAAEDVUdhmmftHjhGqioczX23WYu1WumUSgACVwADzjkIDSf1_eb9ekmGIgQ",
                     "CAACAgQAAxkBAAEDVUlhmmf_k2Nso8cLQ8pPJ_T0wPuH1gACawADzjkIDVlm6mN2kkvQIgQ",
                     "CAACAgQAAxkBAAEDVUthmmgLUpkl1lV8kVL11HNilJTDnQACuAADzjkIDSOB0NvMxc06IgQ",
                     "CAACAgQAAxkBAAEDVU1hmmgnkBSWbZYlRJN8HC4C-JX77QACmwADzjkIDagRPboW9QZtIgQ",
                     "CAACAgIAAxkBAAEDVU9hmmiKZ0cgh40fktmNZa6zZJnmrQAC6AIAArVx2gZSDa62VYCCWyIE",
                     ]